export interface Event {
    id: number;
    uuid: string;
    user_id: number;
    slug: string;
    title: string;
    description: string;
    event_date: string;
    location: string;
    start_time: string;
    start_time_type: string;
    end_time: string;
    end_time_type: string;
    image: string;
    event_venue_name: string;
    event_venue_address_1: string;
    event_venue_address_2: string;
    city: string;
    state: string;
    country: string;
    pincode: string;
    google_map_link: string;
    created_at: string;
    updated_at: string;
    status: number;
    end_minute_time: string;
    start_minute_time: string;
    qr_code: string;
    start_time_format: string;
    feedback: number;
    event_start_date: string;
    event_end_date: string;
    why_attend_info: string | null;
    more_information: string | null;
    t_and_conditions: string | null;
    pdf_path: string | null;
    video_url: string | null;
    printer_count: number | null;
    view_agenda_by: number;
    event_otp: string;
    paid_event: number;
    event_fee: string;
    event_mode: 0 | 1;
    webinar_link: string;
    total_attendee: number;
    total_accepted: number;
    total_not_accepted: number;
    total_rejected: number;
    total_checkedin: number;
    total_checkedin_speaker: number;
    total_speaker: number;
    total_sponsor: number;
    total_checkedin_sponsor: number;
    total_pending_delegate: number;
    break_out: number | string;
    badge_banner?: string | null;
    badge_background_color?: string;
    badge_text_color?: string;
    delegate_tag_color?: string;
    delegate_text_color?: string;
    speaker_tag_color?: string;
    speaker_text_color?: string;
    sponsor_tag_color?: string;
    sponsor_text_color?: string;
    panelist_tag_color?: string;
    panelist_text_color?: string;
}

export interface User {
    id: number;
    email: string;
    name: string;
    access_token: string;
    access_token_type: string;
    company_name: string;
    message: string;
    status: number;
    user_id: number;
    user_uuid: string;
}
